/*
 * File: custom_param.h
 *
 * User customizable oscillator parameter wrapper
 * 
 * 2021 (c) Oleg Burdaev
 * mailto: dukesrg@gmail.com
 *
 */

#pragma once

#include "userosc.h"

#define CUSTOM_PARAM_INIT_ALL(a,b,c,d,e,f,g,h) static const __attribute__((used, section(".hooks"))) uint16_t custom_params[k_num_user_osc_param_id] = {a,b,c,d,e,f,g,h}
#define CUSTOM_PARAM_INIT(a,b,c,d,e,f) CUSTOM_PARAM_INIT_ALL (a,b,c,d,e,f,k_user_osc_param_shape,k_user_osc_param_shiftshape)
#define CUSTOM_PARAM_GET(a) custom_params[a]

#ifndef CUSTOM_PARAM_OFFSET
  #define CUSTOM_PARAM_OFFEST 256
#endif

enum {
  k_user_osc_custom_param_id1 = CUSTOM_PARAM_OFFEST,
  k_user_osc_custom_param_id2,
  k_user_osc_custom_param_id3,
  k_user_osc_custom_param_id4,
  k_user_osc_custom_param_id5,
  k_user_osc_custom_param_id6,
  k_user_osc_custom_param_id7,
  k_user_osc_custom_param_id8,
  k_user_osc_custom_param_id9,
  k_user_osc_custom_param_id10,
  k_user_osc_custom_param_id11,
  k_user_osc_custom_param_id12,
  k_user_osc_custom_param_id13,
  k_user_osc_custom_param_id14,
  k_user_osc_custom_param_id15,
  k_user_osc_custom_param_id16,
  k_user_osc_custom_param_id17,
  k_user_osc_custom_param_id18,
  k_user_osc_custom_param_id19,
  k_user_osc_custom_param_id20,
  k_user_osc_custom_param_id21,
  k_user_osc_custom_param_id22,
  k_user_osc_custom_param_id23,
  k_user_osc_custom_param_id24,
  k_user_osc_custom_param_id25,
  k_user_osc_custom_param_id26,
  k_user_osc_custom_param_id27,
  k_user_osc_custom_param_id28,
  k_user_osc_custom_param_id29,
  k_user_osc_custom_param_id30,
  k_user_osc_custom_param_id31,
  k_user_osc_custom_param_id32,
  k_user_osc_custom_param_id33,
  k_user_osc_custom_param_id34,
  k_user_osc_custom_param_id35,
  k_user_osc_custom_param_id36,
  k_user_osc_custom_param_id37,
  k_user_osc_custom_param_id38,
  k_user_osc_custom_param_id39,
  k_user_osc_custom_param_id40,
  k_user_osc_custom_param_id41,
  k_user_osc_custom_param_id42,
  k_user_osc_custom_param_id43,
  k_user_osc_custom_param_id44,
  k_user_osc_custom_param_id45,
  k_user_osc_custom_param_id46,
  k_user_osc_custom_param_id47,
  k_user_osc_custom_param_id48,
  k_user_osc_custom_param_id49,
  k_user_osc_custom_param_id50,
  k_user_osc_custom_param_id51,
  k_user_osc_custom_param_id52,
  k_user_osc_custom_param_id53,
  k_user_osc_custom_param_id54,
  k_user_osc_custom_param_id55,
  k_user_osc_custom_param_id56,
  k_user_osc_custom_param_id57,
  k_user_osc_custom_param_id58,
  k_user_osc_custom_param_id59,
  k_user_osc_custom_param_id60,
  k_user_osc_custom_param_id61,
  k_user_osc_custom_param_id62,
  k_user_osc_custom_param_id63,
  k_user_osc_custom_param_id64,
  k_user_osc_custom_param_id65,
  k_user_osc_custom_param_id66,
  k_user_osc_custom_param_id67,
  k_user_osc_custom_param_id68,
  k_user_osc_custom_param_id69,
  k_user_osc_custom_param_id70,
  k_user_osc_custom_param_id71,
  k_user_osc_custom_param_id72,
  k_user_osc_custom_param_id73,
  k_user_osc_custom_param_id74,
  k_user_osc_custom_param_id75,
  k_user_osc_custom_param_id76,
  k_user_osc_custom_param_id77,
  k_user_osc_custom_param_id78,
  k_user_osc_custom_param_id79,
  k_user_osc_custom_param_id80,
  k_user_osc_custom_param_id81,
  k_user_osc_custom_param_id82,
  k_user_osc_custom_param_id83,
  k_user_osc_custom_param_id84,
  k_user_osc_custom_param_id85,
  k_user_osc_custom_param_id86,
  k_user_osc_custom_param_id87,
  k_user_osc_custom_param_id88,
  k_user_osc_custom_param_id89,
  k_user_osc_custom_param_id90,
  k_user_osc_custom_param_id91,
  k_user_osc_custom_param_id92,
  k_user_osc_custom_param_id93,
  k_user_osc_custom_param_id94,
  k_user_osc_custom_param_id95,
  k_user_osc_custom_param_id96,
  k_user_osc_custom_param_id97,
  k_user_osc_custom_param_id98,
  k_user_osc_custom_param_id99,
  k_user_osc_custom_param_id100,
  k_user_osc_custom_param_id101,
  k_user_osc_custom_param_id102,
  k_user_osc_custom_param_id103,
  k_user_osc_custom_param_id104,
  k_user_osc_custom_param_id105,
  k_user_osc_custom_param_id106,
  k_user_osc_custom_param_id107,
  k_user_osc_custom_param_id108,
  k_user_osc_custom_param_id109,
  k_user_osc_custom_param_id110,
  k_user_osc_custom_param_id111,
  k_user_osc_custom_param_id112,
  k_user_osc_custom_param_id113,
  k_user_osc_custom_param_id114,
  k_user_osc_custom_param_id115,
  k_user_osc_custom_param_id116,
  k_user_osc_custom_param_id117,
  k_user_osc_custom_param_id118,
  k_user_osc_custom_param_id119,
  k_user_osc_custom_param_id120,
  k_user_osc_custom_param_id121,
  k_user_osc_custom_param_id122,
  k_user_osc_custom_param_id123,
  k_user_osc_custom_param_id124,
  k_user_osc_custom_param_id125,
  k_user_osc_custom_param_id126,
  k_user_osc_custom_param_id127,
  k_user_osc_custom_param_id128
};
